# Generated by Django 2.2.3 on 2019-07-24 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0002_auto_20190724_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='observations',
            field=models.TextField(blank=True, null=True),
        ),
    ]
